hook.Add('Initialize', 'GOpt.RemoveBadHooks', function()
	hook.Remove('RenderScreenspaceEffects', 'RenderColorModify')
	hook.Remove('RenderScreenspaceEffects', 'RenderBloom')
	hook.Remove('RenderScreenspaceEffects', 'RenderToyTown')
	hook.Remove('RenderScreenspaceEffects', 'RenderTexturize')
	hook.Remove('RenderScreenspaceEffects', 'RenderSunbeams')
	hook.Remove('RenderScreenspaceEffects', 'RenderSobel')
	hook.Remove('RenderScreenspaceEffects', 'RenderSharpen')
	hook.Remove('RenderScreenspaceEffects', 'RenderMaterialOverlay')
	hook.Remove('RenderScreenspaceEffects', 'RenderMotionBlur')
	hook.Remove('RenderScene', 'RenderStereoscopy')
	hook.Remove('RenderScene', 'RenderSuperDoF')
	hook.Remove('GUIMousePressed', 'SuperDOFMouseDown')
	hook.Remove('GUIMouseReleased', 'SuperDOFMouseUp')
	hook.Remove('PreventScreenClicks', 'SuperDOFPreventClicks')
	hook.Remove('PostRender', 'RenderFrameBlend')
	hook.Remove('PreRender', 'PreRenderFrameBlend')
	hook.Remove('Think', 'DOFThink')
	hook.Remove('RenderScreenspaceEffects', 'RenderBokeh')
	hook.Remove('NeedsDepthPass', 'NeedsDepthPass_Bokeh')
	hook.Remove('PostDrawEffects', 'RenderWidgets')
	hook.Remove('PostDrawEffects', 'RenderHalos')
	timer.Remove('HostnameThink')
	timer.Remove('CheckHookTimes')
	hook.Remove('Think', 'CheckSchedules')
	hook.Remove('PlayerTick', 'TickWidgets')
end)